# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Use frameworks with static linkage
use_frameworks! :linkage => :static

# Enable React Native Firebase as a static framework
$RNFirebaseAsStaticFramework = true

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'MyProject' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Comment out the Flipper configuration to disable Flipper
  # Note: Flipper is incompatible with `use_frameworks!`
  # flipper_configurations(config)

  target 'MyProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # Ensure React Native dependencies are set up correctly
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Workaround for Flipper compatibility if necessary
    installer.pods_project.targets.each do |target|
      if target.name == 'Flipper'
        target.build_configurations.each do |config|
          config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
      end
    end
  end
end
